---
"$schema": http://json-schema.org/draft-04/hyper-schema
title: GCER - Service
description: Services offered by professionals
stability: prototype
type:
- object
definitions:
  id:
    description: unique identifier of the user
    readOnly: true
    type: integer
  service:
    description: the email of the user
    readOnly: true
    type: string
  type_service:
    description: the kind of the user, admin or professional or secretary
    readOnly: true
    type:
    - string
    - "null"
  price:
    description: the specialty of the professional
    readOnly: true
    type:
    - number
    - "null"
  duration:
    description: the phone of the user
    readOnly: true
    type: integer
  identity:
    anyOf:
    - $ref: /schemata/service#/definitions/id
links:
  - description: List services
    href: /services
    method: GET
    rel: instances
    schema:
      aditionalProperties: true
      properties: {}
      type:
        - object
    targetSchema:
      anyOf:
        - type: array
          items:
            $ref: /schemata/service
        - $ref: /schemata/error
    title: List
properties:
  id:
    $ref: /schemata/service#/definitions/id
  service:
    $ref: /schemata/service#/definitions/service
  type_service:
    $ref: /schemata/service#/definitions/type_service
  price:
    $ref: /schemata/service#/definitions/price
  duration:
    $ref: /schemata/service#/definitions/duration
  specialty:
    $ref: /schemata/specialty#/definitions/specialty
additionalProperties: false
id: schemata/service
